steps:
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        NODE_ENV=production npm ci --quiet --no-fund --no-audit
        NODE_ENV=production npm run build
  - name: 'gcr.io/firebase-ci/firebase-tools'
    args: ['deploy', '--only', 'apphosting']